# Generated by Django 2.2.15 on 2020-08-27 12:00

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0018_auto_20191220_0920'),
        ('wagtail_pages', '0004_homepagespecialproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepagespecialproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_page_specials', to='catalogue.Product'),
        ),
        migrations.CreateModel(
            name='HomePageFeaturedProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='featured_products', to='wagtail_pages.HomePage')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_page_featured', to='catalogue.Product')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
