# Generated by Django 2.2.15 on 2020-08-27 14:33

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_pages', '0005_auto_20200827_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='about',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
    ]
