# Generated by Django 2.2.15 on 2020-08-27 17:12

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0052_pagelogentry'),
        ('wagtailimages', '0022_uploadedimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMediaSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook', models.URLField(blank=True, help_text='Your Facebook page URL', null=True)),
                ('twitter', models.CharField(blank=True, help_text='Your Twitter username, without the @', max_length=255, null=True)),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.Site')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SiteBranding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_color', colorfield.fields.ColorField(default='#000000', max_length=18)),
                ('secondary_color', colorfield.fields.ColorField(default='#000000', max_length=18)),
                ('accent_color', colorfield.fields.ColorField(default='#000000', max_length=18)),
                ('accent_2_color', colorfield.fields.ColorField(default='#000000', max_length=18)),
                ('banner_colour', models.CharField(blank=True, help_text='Fill in a hex colour value', max_length=6, null=True)),
                ('css', models.FileField(blank=True, null=True, upload_to='css/sites/')),
                ('fav_icon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
                ('nav_icon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.Site')),
                ('site_logo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SeoSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_analytics_id', models.CharField(blank=True, default='', max_length=50)),
                ('robots_txt', models.FileField(upload_to='seo/')),
                ('facebook_app_id', models.CharField(blank=True, max_length=100)),
                ('facebook_pixel_id', models.CharField(blank=True, max_length=100)),
                ('brand_name_in_title', models.CharField(blank=True, max_length=50)),
                ('append_brand_name_in_title', models.BooleanField(default=True)),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.Site')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
