# Generated by Django 2.2.15 on 2020-08-28 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0052_pagelogentry'),
        ('multisite', '0004_footerlinks_footerlinksrelatedlink'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FooterLinks',
            new_name='FooterSettings',
        ),
    ]
