# Generated by Django 2.2.15 on 2020-08-28 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multisite', '0005_auto_20200828_0445'),
    ]

    operations = [
        migrations.AddField(
            model_name='footersettings',
            name='about',
            field=models.TextField(blank=True),
        ),
    ]
