# Generated by Django 2.2.15 on 2020-08-28 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0052_pagelogentry'),
        ('multisite', '0007_auto_20200828_0753'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='site',
            field=models.OneToOneField(default=1, editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.Site'),
            preserve_default=False,
        ),
    ]
