# Generated by Django 2.2.15 on 2020-08-28 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multisite', '0009_footerlinksauthorityitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='footerlinksauthorityitem',
            name='height',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='footerlinksauthorityitem',
            name='width',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
