# Generated by Django 2.2.15 on 2020-08-28 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multisite', '0010_auto_20200828_1034'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='pinterest_url',
            field=models.URLField(blank=True),
        ),
    ]
