# Generated by Django 2.2.15 on 2020-09-01 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0052_pagelogentry'),
        ('multisite', '0012_organisation_instagram_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='about_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='wagtailcore.Page'),
        ),
    ]
