# Generated by Django 2.2.15 on 2020-09-01 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0052_pagelogentry'),
        ('multisite', '0013_organisation_about_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='contact_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contact_on_organisation_setting', to='wagtailcore.Page'),
        ),
    ]
