# Generated by Django 2.2.15 on 2020-08-26 17:30

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_auto_20181115_1953'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaypalOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('details', django.contrib.postgres.fields.jsonb.JSONField()),
                ('order_id', models.CharField(max_length=255, unique=True)),
            ],
        ),
    ]
