# Generated by Django 2.2.15 on 2020-08-26 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_paypalorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paypalorder',
            name='details',
            field=models.TextField(),
        ),
    ]
